<?php

/**
 * @file
 * Provides a minimal wrapper around the Mirador Viewer.
 */

// Shorthand for referencing the Mirador library.
define('ISLANDORA_MIRADOR_LIB', 'mirador');

/**
 * Implements hook_menu().
 */
function islandora_mirador_menu() {
  return array(
    'admin/islandora/islandora_viewers/islandora_mirador' => array(
      'title' => 'Islandora Mirador',
      'description' => 'Configure the Islandora Mirador viewer.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_mirador_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_mirador_theme() {
  return array(
    'islandora_mirador_viewer' => array(
      'file' => 'theme/theme.inc',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function islandora_mirador_libraries_info() {
  return array(
    'mirador' => array(
      'name' => ISLANDORA_MIRADOR_LIB,
      'vendor url' => 'http://projectmirador.org/',
      'download url' => 'https://github.com/IIIF/mirador',
      'version arguments' => array(
        'file' => 'bower.json',
        'pattern' => '/"version": "([0-9.]+)"/',
        'lines' => 200,
      ),
      'files' => array(
        'js' => array(
          'build/mirador/mirador.js',
        ),
        'css' => array(
          'build/mirador/css/mirador-combined.min.css',
        ),
      ),
    ),
  );
}


/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_mirador_islandora_viewer_info() {
  return array(
    'islandora_mirador_viewer' => array(
      'label' => t('Islandora Mirador Viewer'),
      'description' => t('Mirador viewer rendering using on-the-fly IIIF manifest generation'),
      'callback' => 'islandora_mirador_viewer',
      'configuration' => 'admin/islandora/islandora_viewers/islandora_mirador',
      'model' => array(
        'islandora:bookCModel',
        'islandora:newspaperIssueCModel',
      ),
    ),
  );
}

/**
 * Viewer.
 */
function islandora_mirador_viewer(array &$params) {
  return theme('islandora_mirador_viewer', $params);
}
