<?php

/**
 * @file
 * Provides a minimal wrapper around the Mirador Viewer.
 */

// Shorthand for referencing the Mirador library.
define('ISLANDORA_MIRADOR_LIB', 'mirador');

/**
 * Implements hook_menu().
 */
function islandora_mirador_menu() {

  return array(
    'islandora_mirador' => array(
      'title' => 'Islandora Mirador Viewer',
      'page callback' => 'theme',
      'page arguments' => array('islandora_mirador_viewer'),
      'access arguments' => array(TRUE),
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora_mirador_manifest/%islandora_object' => array(
      'page callback' => 'islandora_mirador_shared_canvas_manifest_callback',
      'page arguments' => array(1),
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 1),
      'file' => 'includes/callback.inc',
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_mirador_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_mirador_viewer' => array(
      'file' => 'theme/theme.inc',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function islandora_mirador_libraries_info() {
  return array(
    'mirador' => array(
      'name' => ISLANDORA_MIRADOR_LIB,
      'vendor url' => 'http://projectmirador.org/',
      'download url' => 'https://github.com/IIIF/mirador',
      'version arguments' => array(
        'file' => 'bower.json',
        'pattern' => '/"version": "([0-9.]+)"/',
        'lines' => 200,
      ),
      'files' => array(
        'js' => array(
          'build/mirador/mirador.js',
        ),
        'css' => array(
          'build/mirador/css/mirador-combined.min.css',
        ),
      ),
    ),
  );
}
